version: '3'

services:
  {{cookiecutter.project_slug}}_dev:
    container_name: {{cookiecutter.project_slug}}_dev
    image: cloudblueconnect/connect-extension-runner:23.4
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .{{ cookiecutter.project_slug }}_dev.env
  {{cookiecutter.project_slug}}_bash:
    container_name: {{cookiecutter.project_slug}}_bash
    image: cloudblueconnect/connect-extension-runner:23.4
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .{{ cookiecutter.project_slug }}_dev.env
  {{cookiecutter.project_slug}}_test:
    container_name: {{cookiecutter.project_slug}}_test
    image: cloudblueconnect/connect-extension-runner:23.4
    working_dir: /extension
    command: /bin/bash -c "poetry install && pytest --verbose --cov={{cookiecutter.package_slug}} --cov-report=html --cov-report=term-missing:skip-covered"
    volumes:
      - .:/extension
    env_file:
      - .{{ cookiecutter.project_slug }}_dev.env
